version: '2'
services:

  db:
    image: postgres:13.3
    container_name: db
    restart: always
#    volumes:
#      - ./_devdb:/var/lib/postgresql/data
#    user: "${UID}:${GID}"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
